version: '3.5'

services:
  app:
    build:
      context: .
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=app_db
      - DATABASE_PORT=5432
    ports:
      - 3000:3000
    volumes:
      - .:/var/www/app/
    depends_on:
      - app_db

  app_db:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
